@startuml fig_sequence_inscription
skinparam style strictuml
skinparam DefaultFontName Arial
skinparam DefaultFontSize 12
skinparam shadowing false
skinparam SequenceMessageAlignment center

skinparam sequence {
  ArrowColor #A83B3B
  ActorBorderColor #1565C0
  ActorBackgroundColor #BBDEFB
  LifeLineBorderColor #1565C0
  LifeLineBackgroundColor #FFF9C4
  ParticipantBorderColor #4B3A8B
  ParticipantBackgroundColor #D1C4E9
  ParticipantFontStyle bold
}

title Diagramme de séquence système — Inscription

actor "Utilisateur" as U
participant ":Système" as S

U -> S : 1: Demander à s'inscrire
activate S
S --> U : 2: Demander le numéro de téléphone
deactivate S

U -> S : 3: Saisir le numéro de téléphone
activate S
S --> U : 4: Envoyer le code OTP par SMS
deactivate S

U -> S : 5: Saisir le code OTP reçu
activate S

alt Code OTP correct
  S --> U : 6: Valider le code OTP et demander les informations de profil
  deactivate S
  U -> S : 7: Saisir les informations (Nom, Prénom, Mot de passe)
  activate S
  S --> U : 8: Confirmer la création du compte avec succès
else Code OTP incorrect
  S --> U : 9: Afficher un message d'erreur (Code invalide ou expiré)
end
deactivate S

@enduml
